### ISSUE TITLE
 Failed to cleanup intermediate containers

### ISSUE THREAD

**Issue by mskarbek** [containers/buildah#1064]
**Description**
Podman fails to clean up after image build and exits with errors which (obviously) causes problems in Jenkins build pipeline. The same behavior can be observed when building as a root and in rootless mode.

**Steps to reproduce the issue:**
1. Dockerfile: https://gist.github.com/mskarbek/206338d40f6770bb228fe399fe156981#file-dockerfile
2. `podman build -t base .`

**Describe the results you received:**
Podman builds image but exits with errors:
```
(...)
STEP 8: COMMIT base:latest
ERRO[0162] error deleting build container "2ebb70139ee90035ad96cab50e8c1e75fd9e617795460905a22ccdc79104cc80": identifier is not a container
 
Failed to cleanup intermediate containers
```

**Describe the results you expected:**
Podman builds an image without errors.

**Output of `rpm -q buildah` or `apt list buildah`:**
```
buildah-1.3-1.git4888163.fc28.x86_64
```

**Output of `buildah version`:**
```
Version:         1.3
Go Version:      go1.10.3
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      4888163
Built:           Sun Aug  5 13:31:55 2018
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**
```
Version:       0.9.3.1
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**
```
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Twenty Eight)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**
```
Linux rpmq43 4.16.16-300.fc28.x86_64 #1 SMP Sun Jun 17 03:02:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "zfs"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
#override_kernel_check = "true"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# mountopt specifies extra mount options used when mounting the thin devices.
# mountopt = ""

# use_deferred_removal Marking device for deferred removal
# use_deferred_removal = "True"

# use_deferred_deletion Marking device for deferred deletion
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by TomSweeneyRedHat** [comment]
@mskarbek Thanks for reporting the issue and for moving it from Podman.  We'll take a look at it.

**Comment by rhatdan** [comment]
@umohnani8 PTAL. I don't know if anyone has tried this with the zfs driver.

**Comment by mskarbek** [comment]
@rhatdan it's not a ZFS issue, it appears also in a rootless mode when buildah isn't working with ZFS storage backend

**Comment by mskarbek** [comment]
To confirm I just run a build on freshly installed Fedora 28 with default podman config from RPM on XFS/OverlayFS storage backend. Same result.
```
(...)
STEP 8: COMMIT base
ERRO[0267] error deleting build container "9841c4f172dff0d54e8afd7d0f9610487012cd1ef0bbe8ea7fc6f2169e7092b6": identifier is not a container
 
Failed to cleanup intermediate containers
```
Fails on both podman `0.9.1` and `0.9.3.1` form `updates-testing` repo.

**Comment by mskarbek** [comment]
Another test with podman 0.9.4 from Rawhide - same result.

```
STEP 8: COMMIT base
ERRO[0235] error deleting build container "cfe5bd8eaf1b75c52e53e7686cb00c61a9c1baf44dcb77e00fa2063008c0e8a3": identifier is not a container
 
Failed to cleanup intermediate containers
```

```
# podman info
host:
  Conmon:
    package: podman-0.9.4-3.dev.gite7e81e6.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 28fb00a937906ec07b1266ad7b5c3254617e96d0-dirty'
  MemFree: 14190583808
  MemTotal: 16024010752
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: ip-10-64-163-189.us-west-2.compute.internal
  kernel: 4.18.10-200.fc28.x86_64
  os: linux
  uptime: 1h 6m 45.56s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 4
  RunRoot: /var/run/containers/storage
```

Surprisingly I did `buildah bud -t base .` with Dockerfile from the issue - works fine so it may be not a buildah fault after all.

```
(..)
STEP 6: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.mountopt=nodev,overlay.override_kernel_check=true]localhost/base:latest
Getting image source signatures
Copying blob sha256:1044a8ec8f4ea7ba2267aeebe20a9f2d440f9f337b50e112f3ed9465e1599852
 55.70 MiB / 55.70 MiB [====================================================] 2s
Copying config sha256:7bb6969ef2f9775ae1ea255bf92285309c9f00bf27a3f5e6909cdb54a4fce80a
 355 B / 355 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
--> 7bb6969ef2f9775ae1ea255bf92285309c9f00bf27a3f5e6909cdb54a4fce80a
# echo $?
0
```

```
# buildah version
Version:         1.3
Go Version:      go1.10.3
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      4888163
Built:           Sun Aug  5 11:31:55 2018
OS/Arch:         linux/amd64
```
At this point, I'll stop spamming this issue.

**Comment by umohnani8** [comment]
@mskarbek could you update your buildah to 1.4 and try it out. I just tried it here with the Dockerfile you linked and it works fine for me on both buildah 1.4 and podman 0.9.4 and I am using overlay as storage driver.
Also the reason it worked for you on buildah is because buildah doesn't build with layers by default but podman does. So if you check your image built from buildah you would see that you have no intermediate images. Please try this ut with buildah 1.4 (set the --layers flag to true --> `buildah bud --layers -t myimage .`) and let me know what you see.

**Comment by mskarbek** [comment]
```
# uname -a
Linux clw-node01 4.18.11-200.fc28.x86_64 #1 SMP Sun Sep 30 15:31:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# buildah version
strconv.ParseInt: parsing "": invalid syntax
# buildah -v
buildah version 1.4-dev (image-spec 1.0.0, runtime-spec 1.0.0)
# rpm -q buildah
buildah-1.4-2.dev.git19e44f0.fc30.x86_64
# buildah bud --layers -t base .
(...)
STEP 8: COMMIT base
ERRO[0318] error deleting build container "f67a4c33877e2dca73102774a19942c758500d45b829d583e84450d4ea978e8b": identifier is not a container
 
Failed to cleanup intermediate containers
```

```
podman info
host:
  Conmon:
    package: podman-0.9.4-3.dev.gite7e81e6.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 28fb00a937906ec07b1266ad7b5c3254617e96d0-dirty'
  MemFree: 31021244416
  MemTotal: 33633083392
  OCIRuntime:
    package: runc-1.0.0-51.dev.gitfdd8055.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: clw-node01
  kernel: 4.18.11-200.fc28.x86_64
  os: linux
  uptime: 2h 21m 55.9s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 4
  RunRoot: /var/run/containers/storage
```
So in addition to the intermediate containers `version` command in `buildah` stoped working.
