### ISSUE TITLE
buildah inspect errors with "vfs driver does not support mount options" but podman inspect works fine

### ISSUE THREAD

**Issue by TomasTomecek** [containers/buildah#1251]
**Description**

`buildah inspect` errors out while `podman inspect` works just fine

**Steps to reproduce the issue:**
https://github.com/containers/buildah/issues/1251#issuecomment-451416452

**Describe the results you received:**
```
vfs driver does not support mount options
vfs driver does not support mount options
```

**Output of `buildah version`:**
```
Version:         1.5
Go Version:      go1.11.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

Host: F29
Environment: F29, openshift pod running in privileged mode

**More info**

```
[root@ab-pod /]# uname -a
Linux ab-pod 4.19.7-300.fc29.x86_64 #1 SMP Wed Dec 5 22:21:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[root@ab-pod /]# cat /etc/containers/storage.conf
[storage]

# Default Storage Driver
driver = "vfs"

# Primary Read/Write location of container storage
graphroot = "/tmp/containers"

[root@ab-pod /]# id
uid=0(root) gid=0(root) groups=0(root)
```

I only changed those two storage opts.

**Comment by TomasTomecek** [comment]
same thing happens with `buildah from`, while `podman run` works fine

**Comment by TomasTomecek** [comment]
Tried buildah 1.6, the same result:
```
vfs driver does not support mount options                                                                                                                            
vfs driver does not support mount options
```

**Comment by TomasTomecek** [comment]
Here are the complete logs: https://paste.fedoraproject.org/paste/7zMBAVc0SxFgQfwNpsE6cQ

`podman info` output:
```
store:                                                    
  ContainerStore:                                                                         
    number: 0                                               
  GraphDriverName: vfs                                                                                                                                                
  GraphOptions: null                                                         
  GraphRoot: /tmp/containers                                                                                                                                          
  GraphStatus: {}                                                                                                                                                    
  ImageStore:                                                                  
    number: 0                                                                             
  RunRoot: /var/run/containers/storage 
```
