### ISSUE TITLE
Question: buildah push using k8s secret

### ISSUE THREAD

**Issue by cmoulliard** [containers/buildah#1606]
## Question

Does buildah supports to perform a `push` using a k8s secret mounted using a serviceaccount  to be auth with the registry ?

Example 

- ServiceAccount
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: basic-user-pass
```

- Secret
```
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: QUAY_ROBOT_USER
  password: QUAY_ROBOT_PWD
```

Next, we create a Pod where the `serviceaccount` is used and where we will do a:
 `buildah bud` followed by `buildah push`
