### ISSUE TITLE
issue building from branch of git repo context

### ISSUE THREAD

**Issue by dustymabe** [containers/buildah#1934]
I'm having an issue trying to specify a branch to build from like described [here](https://docs.docker.com/engine/reference/commandline/build/) under **Build Syntax Suffix**.

Here is an example where I am trying to build from the `dusty` branch: 

```
[vagrant@vanilla-f31 ~]$ sudo /usr/bin/podman build -t simple-kmod-a8c6682:5.3.7-300.fc31.x86_64 --label=name=simple-kmod --build-arg KVER=5.3.7-300.fc31.x86_64 --build-arg KMODVER=a8c6682 git://github.com/dustymabe/kvc-simple-kmod#dusty
Error: error prepping temporary context directory: exit status 128
[vagrant@vanilla-f31 ~]$ 
[vagrant@vanilla-f31 ~]$ sudo /usr/bin/podman build -t simple-kmod-a8c6682:5.3.7-300.fc31.x86_64 --label=name=simple-kmod --build-arg KVER=5.3.7-300.fc31.x86_64 --build-arg KMODVER=a8c6682 https://github.com/dustymabe/kvc-simple-kmod#dusty
Error: no FROM statement found
```

Sorry for being brief but I don't have much time right now to provide all the information needed.

**Version Info**

```
[vagrant@vanilla-f31 ~]$ rpm -q podman
podman-1.6.2-2.fc31.x86_64
[vagrant@vanilla-f31 ~]$ sudo podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64

```

**Output of `podman info`:**

<details>

```
[vagrant@vanilla-f31 ~]$ sudo podman info
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.1-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 5e0eadedda9508810235ab878174dca1183f4013'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 3720368128
  MemTotal: 4126642176
  OCIRuntime:
    name: crun
    package: crun-0.10.2-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.2
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: vanilla-f31
  kernel: 5.3.7-300.fc31.x86_64
  os: linux
  rootless: false
  uptime: 15m 9.03s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 14
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

</details>
