### ISSUE TITLE
error extracting layer : no such device

### ISSUE THREAD

**Issue by gregoryboue** [containers/buildah#2382]
**Description**

I'm using buildah image v1.14.8 from https://quay.io/repository/buildah/stable, and I'm getting an error on buildah bud with a  multi-stage build FROM image .

At the first RUN instruction I had an error : 
```
error committing container for step .... error copying layers and metadata for container ..... : Error initializing source containers-storage:.....-working-container: error extracting layer ".....": no such device
```

I did a buildah bud with the following tags of quay repository : "v1.9.0",  "v1.9.1", "v1.9.2", "v1.10.1", "v1.11.6",  "v1.12.0", "v1.14.0", "v1.14.3", "v1.14.8"

It's only works fine with v1.11.6 tag, for version after i get the error above, and for version before 1.11.6 I get this error : 
```
process exited with error: fork/exec /bin/sh: no such file or directorysubprocess exited with status 1
```

**Steps to reproduce the issue:**
1. Create the following Dockerfile

```docker
FROM xxxx/linux/ubuntu:16.04 as builder

RUN apt-get update && \
    apt-get install -y multistrap 

COPY multistrap-docker-ubuntu-16.04-LTS-amd64.conf /home/
COPY buildOSArchive.sh .

RUN chmod 755 buildOSArchive.sh && ./buildOSArchive.sh

# Image Ubuntu 16.04 LTS
FROM scratch

COPY --from=builder  /home/UbuntuDist /

RUN apt-get update \
        && apt-get install -y --no-install-recommends ca-certificates \
        && apt-get -y -q autoclean && apt-get -y -q autoremove \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*  
ADD certificates.crt /usr/local/share/ca-certificates/

RUN update-ca-certificates
```
2. Build this image with command `buildah bud --tls-verify=false --format docker --layers ---pull -f Dockerfile --tag xxx/ubuntu:16.04-1 .`
3. Create the following dockerfile 
```docker
FROM xxx/linux/ubuntu:16.04

ENV TZ Europe/Paris
ENV DEBIAN_FRONTEND noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#Creation user applicatif
RUN groupadd -g 1002 buildtool \
&& groupadd -g 5313 docker \
&& useradd -m -d /home/buildtool -g buildtool -g docker -u 1002 buildtool \
&& useradd  -g buildtool -u 5313 docker


ENV PACKAGES  curl wget tzdata git build-essential binutils software-properties-common cmake autoconf automake gcc bison flex libpq-dev libwebsockets-dev

RUN set -xe \
   apt-get update \
  && apt-get upgrade -y \
  && apt-get update \
  && apt-get install -y --no-install-recommends $PACKAGES \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get clean
  

CMD bash
```
4. Build this image in quay buildah/stable:v1.14.8 container with command `buildah --debug bud --tls-verify=false --format docker --layers --pull -f Dockerfile --tag xxxx/c:7 .`

**Describe the results you received:**

At the first Dockerfile RUN instruction ```
error committing container for step .... error copying layers and metadata for container ..... : Error initializing source containers-storage:.....-working-container: error extracting layer ".....": no such device
```

**Describe the results you expected:**

Buildah bud ok


**Output of `buildah version`:**

```
+ buildah version
Version:         1.14.8
Go Version:      go1.14
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.4.3
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Comment by gregoryboue** [comment]
In additional information, i'm running stable/buildah container on Kubernetes (AKS) with privileged security context.

I did several try, the build is ok with --storage-driver=vfs with v1.14.8.
The things that i can't stand are :

- Why it's only work with 1.11.6 with overlayfs ?
- Why I have only (for the moment) the problem for this image ?

**Comment by TomSweeneyRedHat** [comment]
@giuseppe any thoughts?

**Comment by gregoryboue** [comment]
Any news about this ?

**Comment by rhatdan** [comment]
Are you still able to reproduce with the latest upstream including newer versions of fuse-overlayfs and crun?

**Comment by gregoryboue** [comment]
@rhatdan you mean with this image :  https://quay.io/repository/buildah/stable:latest ?

**Comment by rhatdan** [comment]
Yes

**Comment by gregoryboue** [comment]
@rhatdan , I tried with the latest : 

+ buildah version
Version:         1.15.0
Go Version:      go1.14.3
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.1
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64

I had exactly the same error : *error initializing source containers-storage:ubuntu-working-container: error extracting layer "4c4fbdddd435ea77d37837b63d6e4f0722af4e46d46bee867c1de5e7d4baca41": no such device*

**Comment by rhatdan** [comment]
What is the podman command you are using to launch the container?

**Comment by gregoryboue** [comment]
The container is hosted on kubernetes cluster (aks) i instantiate it with jenkins kubernetes plugin : 

```yaml
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
  name: "poddocker-d56b709b-7ca0-4096-b724-bd82d644ab0e-f53s7-gcdx9"
spec:
  containers:
  - args:
    - "********"
    - "poddocker-d56b709b-7ca0-4096-b724-bd82d644ab0e-f53s7-gcdx9"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "xxxxxx"
    - name: "JENKINS_AGENT_NAME"
      value: "poddocker-d56b709b-7ca0-4096-b724-bd82d644ab0e-f53s7-gcdx9"
    - name: "JAVA_OPTS"
      value: "-Xms128m -Xmx512m -Dfile.encoding=UTF-8"
    - name: "JENKINS_NAME"
      value: "poddocker-d56b709b-7ca0-4096-b724-bd82d644ab0e-f53s7-gcdx9"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "JENKINS_URL"
      value: "https://xxxx/"
    image: "registry-proxy/jenkins/jnlp-slave:4.3-4"
    imagePullPolicy: "Always"
    name: "jnlp"
    resources:
      limits:
        memory: "640Mi"
        cpu: "2"
      requests:
        memory: "192Mi"
        cpu: "200m"
    securityContext:
      privileged: false
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - command:
    - "cat"
    image: "registry-proxy/buildah/stable:latest"
    imagePullPolicy: "Always"
    name: "buildah"
    resources:
      limits:
        memory: "2Gi"
        cpu: "2"
      requests:
        memory: "1Gi"
        cpu: "200m"
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  dnsPolicy: "Default"
  nodeSelector: {}
  restartPolicy: "Never"
  securityContext:
    runAsUser: 0
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"
```
