### ISSUE TITLE
Non-Root buildah issues in Tekton Pipeline

### ISSUE THREAD

**Issue by cgruver** [containers/buildah#2629]
I am attempting to adapt the tutorial: https://github.com/containers/buildah/blob/master/docs/tutorials/05-openshift-rootless-bud.md to work within a Tekton Task.

I am running into the following error:

```bash
ERRO Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:12 for /var/spool/mail): lchown /var/spool/mail: invalid argument
```

_*Relevant Info*_

* The `pipeline` service account has been granted `nonroot` privileges 

```bash
oc adm policy add-scc-to-user nonroot -z pipeline
```

I verified that this works with the tutorial above, rather than `anyuid`

* Buildah - from `quay.io/buildah/stable:latest`

* Modified with - Dockerfile:

```bash
FROM quay.io/buildah/stable:latest
RUN touch /etc/subgid /etc/subuid \
&& chmod g=u /etc/subgid /etc/subuid /etc/passwd 
```

* Buildah Version:

```bash
sh-5.0$ buildah version
Version:         1.15.1
Go Version:      go1.14.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.1
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

* Tekton Step in Task:

```yaml
- name: build-image
  image: image-registry.openshift-image-registry.svc:5000/openshift/buildah:noroot
  imagePullPolicy: Always
  script: |
    echo "tekton:x:$(id -u):0:tekton user:${HOME}:/sbin/nologin" >> /etc/passwd
    echo tekton:10000:65536 > /etc/subuid
    echo tekton:10000:65536 > /etc/subgid
    export BUILDAH_ISOLATION=chroot
    mkdir -p ${HOME}/.config/containers
    echo "[storage]" > ${HOME}/.config/containers/storage.conf
    echo "driver=\"vfs\"" >> ${HOME}/.config/containers/storage.conf
    CONTAINER=$(buildah --tls-verify=$(params.tlsVerify) from image-registry.openshift-image-registry.svc:5000/openshift/jdk-ubi-minimal:8.1 )
    buildah copy ${CONTAINER} ./target/lib/* /deployments/lib/
    buildah copy ${CONTAINER} ./target/app-runner.jar /deployments/app.jar
    buildah commit ${CONTAINER} $(params.destinationImage)
    buildah unmount ${CONTAINER}
  env:
    - name: user.home
       value: /tekton/home
  workingDir: "/workspace/source"
```

* User in Pod terminal:

```bash
sh-5.0$ id
uid=1000640000(tekton) gid=0(root) groups=0(root),1000640000
sh-5.0$ cat /etc/subgid
tekton:10000:65536
sh-5.0$ cat /etc/subgid
tekton:10000:65536
sh-5.0$ whoami
tekton
sh-5.0$ echo $BUILDAH_ISOLATION
chroot
```

* `newuidmap` and `newgidmap` do not appear to be working

```bash
sh-5.0$ buildah unshare cat /proc/self/uid_map
         0 1000640000          1
sh-5.0$ buildah unshare cat /proc/self/gid_map
         0          0          1
```

**Comment by cgruver** [comment]
Some additional info from within the running pod:

```bash
sh-5.0$ id
uid=1000640000(tekton) gid=0(root) groups=0(root),1000640000
sh-5.0$ uname -a
Linux build-and-deploy-dgtml2-build-69xhf-pod-p6s49 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Buildah can initiate a new image, but cannot pivot to it via `unshare`

```bash
sh-5.0$ buildcontainer=$(buildah from scratch)
sh-5.0$ buildah unshare --mount buildmount=$buildcontainer
ERRO no command specified                         
ERRO exit status 1                                
sh-5.0$ 
```

Buildah can commit the empty image:

```bash
sh-5.0$ buildah commit $buildcontainer test-image
Getting image source signatures
Copying blob 5f70bf18a086 done  
Copying config dd38cf9b6f done  
Writing manifest to image destination
Storing signatures
dd38cf9b6fdd4a5266cc4ff9748733f9cb64efedd868a087931f4059b87634e6
sh-5.0$ buildah images
REPOSITORY             TAG      IMAGE ID       CREATED          SIZE
localhost/test-image   latest   dd38cf9b6fdd   11 seconds ago   2.03 KB
```

Buildah cannot pull an image:

```bash
sh-5.0$ newcontainer=$(buildah from registry.access.redhat.com/ubi7/ubi-minimal)
Getting image source signatures
Copying blob 0dc69daaa449 done  
Copying blob c13bd28f35dc done  
Copying config 259d30d7f9 done  
Writing manifest to image destination
Storing signatures
ERRO Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument 
Getting image source signatures
Copying blob 0dc69daaa449 done  
Copying blob c13bd28f35dc done  
Copying config 259d30d7f9 done  
Writing manifest to image destination
Storing signatures
ERRO Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument 
Getting image source signatures
Copying blob 0dc69daaa449 done  
Copying blob c13bd28f35dc done  
Copying config 259d30d7f9 done  
Writing manifest to image destination
Storing signatures
ERRO Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument 
Getting image source signatures
Copying blob 0dc69daaa449 done  
Copying blob c13bd28f35dc done  
Copying config 259d30d7f9 done  
Writing manifest to image destination
Storing signatures
ERRO Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument 
Error committing the finished image: error adding layer with blob "sha256:c13bd28f35dce9b6847f2bbdd405504b3ee7a72289591565b02d3356e0b981b8": ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument
ERRO exit status 125                              
```

**Comment by cgruver** [comment]
Yet more information:

newgidmap and newuidmap are clearly failing to run do to permissions of some sort.

```bash
sh-5.0$ buildah --log-level debug unshare sh
DEBU running [buildah-in-a-user-namespace --log-level debug unshare sh] with environment [user.home=/tekton/home KUBERNETES_SERVICE_PORT_HTTPS=443 HOME_LIBRARY_CATALOG_PORT_8080_TCP_ADDR=172.30.124.243 KUBERNETES_SERVICE_PORT=443 HOSTNAME=build-and-deploy-0i4nj1-build-xjdkh-pod-hg9jb NSS_SDB_USE_CACHE=no DISTTAG=f32container PWD=/workspace/source container=oci HOME_LIBRARY_CATALOG_PORT_8080_TCP_PORT=8080 HOME=/tekton/home KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443 FGC=f32 BUILDAH_ISOLATION=chroot TERM=xterm HOME_LIBRARY_CATALOG_SERVICE_PORT=8080 HOME_LIBRARY_CATALOG_SERVICE_HOST=172.30.124.243 SHLVL=1 HOME_LIBRARY_CATALOG_PORT_8080_TCP=tcp://172.30.124.243:8080 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1 KUBERNETES_SERVICE_HOST=172.30.0.1 KUBERNETES_PORT=tcp://172.30.0.1:443 HOME_LIBRARY_CATALOG_PORT=tcp://172.30.124.243:8080 KUBERNETES_PORT_443_TCP_PORT=443 HOME_LIBRARY_CATALOG_PORT_8080_TCP_PROTO=tcp HOME_LIBRARY_CATALOG_SERVICE_PORT_8080_TCP=8080 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/bin/buildah TMPDIR=/var/tmp _CONTAINERS_USERNS_CONFIGURED=1], UID map [{ContainerID:0 HostID:1000640000 Size:1} {ContainerID:1 HostID:1 Size:65536} {ContainerID:65537 HostID:1100000000 Size:65536}], and GID map [{ContainerID:0 HostID:0 Size:1} {ContainerID:1 HostID:1 Size:65536} {ContainerID:65537 HostID:1100000000 Size:65536}] 
WARN error running newgidmap: fork/exec /usr/bin/newgidmap: operation not permitted:  
WARN falling back to single mapping               
WARN error running newuidmap: fork/exec /usr/bin/newuidmap: operation not permitted:  
WARN falling back to single mapping
```

**Comment by cgruver** [comment]
I observe the following securityContext set on the Pod:

```yaml
  securityContext:
    seLinuxOptions:
      level: 's0:c25,c20'
    runAsUser: 1000640000
    runAsNonRoot: true
    fsGroup: 1000640000
```

Each Container in the pod has the following security context:

```yaml
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000640000
```

Is this potentially the issue?

**Comment by TomSweeneyRedHat** [comment]
@giuseppe any thoughts?

**Comment by cgruver** [comment]
For comparison:

When I run the image built from the tutorial with: `adm policy add-scc-to-user nonroot -z buildah-sa` applied as security context for the service account, I see the following:

```yaml
securityContext:
    seLinuxOptions:
      level: 's0:c25,c0'
```

```yaml
     securityContext:
        capabilities:
          drop:
            - MKNOD
```

I'm looking into the Tekton default configuration to see where it is apply a default pod template of some kind.

**Comment by cgruver** [comment]
Got it!!!

Added a podTemplate to my Tekton Pipeline run:

```yaml
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: ${APP_NAME}-pipeline-run
    spec:
      pipelineRef: 
        name: build-and-deploy
      podTemplate:
        securityContext:
          seLinuxOptions:
            level: 's0:c25,c20'
          runAsUser: 1000640000
          fsGroup: 1000640000
      params:
      - name: appName
        value: ${APP_NAME}
      - name: git-repo
        value: ${GIT_REPOSITORY}
      - name: git-branch
        value: ${GIT_BRANCH}
      - name: destinationImage
        value: "image-registry.openshift-image-registry.svc:5000/${NAME_SPACE}/${APP_NAME}:latest"
```

`adm policy add-scc-to-user nonroot -z pipeline`

It works!  Non-Root buildah in a Tekton pipeline.  You don't have to run a privileged container.

I'll write this up after more testing.
