### ISSUE TITLE
Overlay disk size management for Buildah

### ISSUE THREAD

**Issue by abudavis** [containers/buildah#2791]
When using the buildah template in OpenShift Pipelines (Tekton) to build an image without a pre-defined PVC, we can see it uses the overlay disk (ephemeral storage) as shown below, however how do we ensure this disk is managed properly, for example, do not want this disk to run full! Thoughts?

Buildah on OpenShift Pipelines : https://github.com/openshift/pipelines-catalog/tree/master/task/buildah-pr/0.1
OpenShift Pipelines version: 1.1.2
Openshift version: 4.6.3
More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage

```
---
+ df -h /var/lib/containers
Filesystem Size Used Avail Use% Mounted on
overlay 512G 20G 493G 4% /
+ ls -ltr /var/lib/containers
total 0
drwxr-xr-x. 2 root root 6 Oct 2 20:53 sigstore
+ buildah --storage-driver vfs bud --tls-verify=false -f /workspace/sourcerepos/tip000-ace-cicd-templates/pipeline/dockerfiles/app.Dockerfile -t image-registry.openshift-image-registry.svc:5000/ace/app:latest /workspace/source/artefacts
STEP 1: FROM image-registry.openshift-image-registry.svc:5000/ace/app:latest
Getting image source signatures
Copying blob sha256:abd3c5f43d014a439cc6056575c24c8f4df4e819b90e7db4abccce827a6c8453
Copying blob sha256:3ccbd95c2a8b98f9c83525c43bb8bed330dd72b3c8a668100c9e292abad5862f
...
---
```

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by nalind** [comment]
Since we don't delete things (intermediate images, other images) unless we're specifically asked to, I'd suggest mounting an `emptyDir` volume on `/var/lib/containers` so that the storage being used during the build will get cleaned up when the build is finished.

If your node is using `overlay` for running containers, and you're running the build with privileges, we would default to attempting to use `overlay`, only to be denied by the kernel because overlay-on-overlay isn't allowed.  Because `emptyDir` volumes tend to be random ordinary directories on the node, it would avoid that problem as well.

**Comment by abudavis** [comment]
That worked thanks ! :)

My config:

```
steps:
    - name: build
      image: quay.io/buildah/stable:latest
      securityContext:
        privileged: true
      script: |
        buildah --storage-driver vfs bud \
      -f /workspace/sourcerepos/tip000-ace-cicd-templates/pipeline/dockerfiles/app.Dockerfile -t image-registry.openshift-  image-registry.svc:5000/ns/app:latest /workspace/source/artefacts
        buildah --storage-driver vfs push \
          --tls-verify=false \
          image-registry.openshift-image-registry.svc:5000/ns/appfinal:latest
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
 volumes:
    - name: varlibcontainers
       emptyDir: {}
```
