### ISSUE TITLE
Container images not detected after 'buildah bud' on Kubernetes

### ISSUE THREAD

**Issue by aetherith** [containers/buildah#3082]
**Description**
I am trying to use the `buildah/stable:v1.19.6` container to build and push a container image from within a Kubernetes `Job`. When I run `buildah bud` the output seems to indicate that the image is pulled and tagged locally but when `buildah images` is run immediately afterwards no images are reported. This means that a further call to `buildah push` fails due to unknown image ID.

**Steps to reproduce the issue:**
1. Execute the chart found at github.com/aetherith/helm-container-build with the rendered result below. Sensitive information replaced with `<REDACTED>` and image namespace with `example`.

**Edited per comment below**
```yaml
---
# Source: container-build/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-container-build
  labels:
    helm.sh/chart: container-build-0.1.0
    app.kubernetes.io/name: container-build
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "v1.19.6"
    app.kubernetes.io/managed-by: Helm
---
# Source: container-build/templates/registryAuthSecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-container-build-source-auth
  labels:
    helm.sh/chart: container-build-0.1.0
    app.kubernetes.io/name: container-build
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "v1.19.6"
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://docker.io": {
          "username": "<REDACTED>",
          "password": "<REDACTED>",
          "auth": "<REDACTED>"
        }
      }
    }
---
# Source: container-build/templates/registryAuthSecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-container-build-dest-auth
  labels:
    helm.sh/chart: container-build-0.1.0
    app.kubernetes.io/name: container-build
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "v1.19.6"
    app.kubernetes.io/managed-by: Helm
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://docker.io": {
          "username": "<REDACTED>",
          "password": "<REDACTED>",
          "auth": "<REDACTED>"
        }
      }
    }
---
# Source: container-build/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-container-build
  labels:
    helm.sh/chart: container-build-0.1.0
    app.kubernetes.io/name: container-build
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "v1.19.6"
    app.kubernetes.io/managed-by: Helm
data:
  Dockerfile: |
    FROM docker.io/library/ubuntu:20.10
---
# Source: container-build/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-container-build
  labels:
    helm.sh/chart: container-build-0.1.0
    app.kubernetes.io/name: container-build
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "v1.19.6"
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
    spec:
      serviceAccountName: example-container-build
      securityContext:
        {}
      containers:
        - name: container-build
          securityContext:
            {}
          image: "quay.io/buildah/stable:v1.19.6"
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/bin/bash"
            - "-cx"
          args:
            - >
              buildah bud
              --file Dockerfile
              --authfile /root/source-auth
              --storage-driver vfs
              --format docker
              --tag "example/ubuntu:latest"
              --debug
              /build
              &&
              buildah images --all
              &&
              buildah push
              --authfile /root/destination-auth
              "example/ubuntu:latest"
              docker://docker.io/example/ubuntu:latest
          volumeMounts:
            - name: cache
              mountPath: /var/lib/containers
            - name: build
              mountPath: /build
            - name: config
              mountPath: /build/Dockerfile
              subPath: Dockerfile
            - name: source-auth
              mountPath: "/root/source-auth"
              subPath: source-auth
              readOnly: true
            - name: destination-auth
              mountPath: "/root/destination-auth"
              subPath: destination-auth
              readOnly: true
          resources:
            {}
      volumes:
        - name: cache
          emptyDir: {}
        - name: build
          emptyDir: {}
        - name: config
          configMap:
            name: example-container-build
        - name: source-auth
          secret:
            secretName: example-container-build-source-auth
            items:
              - key: .dockerconfigjson
                path: source-auth
        - name: destination-auth
          secret:
            secretName: example-container-build-dest-auth
            items:
              - key: .dockerconfigjson
                path: destination-auth
      restartPolicy: Never
```
 
**Expected Result**
The image is built and uploaded to DockerHub. This sequence of commands seems to work as expected on a rootless Fedora 33 install of `buildah`.

**Actual Result**
The image is downloaded and reports that it is tagged correctly, however `buildah images` does not report it existing and `buildah push` cannot push the image. 
```
% kubectl logs -f test-container-build-c4wpv
+ buildah bud --file Dockerfile --authfile /root/source-auth --storage-driver vfs --format docker --tag example/ubuntu:latest --debug /build
level=debug msg="running [buildah-in-a-user-namespace bud --file Dockerfile --authfile /root/source-auth --storage-driver vfs --format docker --tag example/ubuntu:latest --debug /build] with environment [KUBERNETES_SERVICE_PORT_HTTPS=443 KUBERNETES_SERVICE_PORT=443 HOSTNAME=test-container-build-c4wpv DISTTAG=f33container PWD=/ container=oci HOME=/root KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443 FGC=f33 BUILDAH_ISOLATION=chroot SHLVL=1 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1 KUBERNETES_SERVICE_HOST=10.43.0.1 KUBERNETES_PORT=tcp://10.43.0.1:443 KUBERNETES_PORT_443_TCP_PORT=443 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/bin/buildah TMPDIR=/var/tmp _CONTAINERS_USERNS_CONFIGURED=1], UID map [{ContainerID:0 HostID:0 Size:4294967295}], and GID map [{ContainerID:0 HostID:0 Size:4294967295}]"
level=debug msg="Pull Policy for pull [PullIfNewer]"
level=debug msg="[graphdriver] trying provided driver \"vfs\""
level=debug msg="reading local Dockerfile \"/build/Dockerfile\""
level=debug msg="base: \"docker.io/library/ubuntu:20.10\""
level=debug msg="FROM \"docker.io/library/ubuntu:20.10\""
STEP 1: FROM docker.io/library/ubuntu:20.10
level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
level=debug msg="Loading registries configuration \"/etc/containers/registries.conf.d/shortnames.conf\""
level=debug msg="registry \"docker.io\" is not listed in registries configuration \"/etc/containers/registries.conf\", assuming it's not blocked"
level=debug msg="parsed reference into \"[vfs@/var/lib/containers/storage+/run/containers/storage]docker.io/library/ubuntu:20.10\""
level=debug msg="parsed reference into \"[vfs@/var/lib/containers/storage+/run/containers/storage]docker.io/library/ubuntu:20.10\""
level=debug msg="copying \"docker://ubuntu:20.10\" to \"docker.io/library/ubuntu:20.10\""
level=debug msg="Trying to access \"docker.io/library/ubuntu:20.10\""
level=debug msg="Trying to access \"docker.io/library/ubuntu:20.10\""
level=debug msg="Returning credentials from /root/source-auth"
level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration"
level=debug msg=" Using \"default-docker\" configuration"
level=debug msg=" No signature storage configuration found for docker.io/library/ubuntu:20.10, using built-in default file:///var/lib/containers/sigstore"
level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io"
level=debug msg="GET https://registry-1.docker.io/v2/"
level=debug msg="Ping https://registry-1.docker.io/v2/ status 401"
level=debug msg="GET https://auth.docker.io/token?account=<REDACTED>&scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io"
level=debug msg="GET https://registry-1.docker.io/v2/library/ubuntu/manifests/20.10"
level=debug msg="Content-Type from manifest GET is \"application/vnd.docker.distribution.manifest.list.v2+json\""
level=debug msg="Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb"
level=debug msg="Source is a manifest list; copying (only) instance sha256:b10694fc29f6c511a7e8b7c1a7e3330c91c6c7addf2cc3b9627413c4a19d261f for current system"
level=debug msg="GET https://registry-1.docker.io/v2/library/ubuntu/manifests/sha256:b10694fc29f6c511a7e8b7c1a7e3330c91c6c7addf2cc3b9627413c4a19d261f"
level=debug msg="Content-Type from manifest GET is \"application/vnd.docker.distribution.manifest.v2+json\""
level=debug msg="IsRunningImageAllowed for image docker:docker.io/library/ubuntu:20.10"
level=debug msg=" Using default policy section"
level=debug msg=" Requirement 0: allowed"
level=debug msg="Overall: allowed"
level=debug msg="Downloading /v2/library/ubuntu/blobs/sha256:bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c"
level=debug msg="GET https://registry-1.docker.io/v2/library/ubuntu/blobs/sha256:bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c"
Getting image source signatures
level=debug msg="Reading /var/lib/containers/sigstore/library/ubuntu@sha256=b10694fc29f6c511a7e8b7c1a7e3330c91c6c7addf2cc3b9627413c4a19d261f/signature-1"
level=debug msg="Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json]"
level=debug msg="... will first try using the original manifest unmodified"
level=debug msg="Downloading /v2/library/ubuntu/blobs/sha256:8f57cefb68887255bfffe7e6ddee55ac93c131dc9ceedf6bbf1dfec7836abe75"
level=debug msg="GET https://registry-1.docker.io/v2/library/ubuntu/blobs/sha256:8f57cefb68887255bfffe7e6ddee55ac93c131dc9ceedf6bbf1dfec7836abe75"
level=debug msg="Downloading /v2/library/ubuntu/blobs/sha256:de21e52cfb21f634ab48959716b6f989328d5324043d6a259ca15df8a04e7f8d"
level=debug msg="GET https://registry-1.docker.io/v2/library/ubuntu/blobs/sha256:de21e52cfb21f634ab48959716b6f989328d5324043d6a259ca15df8a04e7f8d"
level=debug msg="Downloading /v2/library/ubuntu/blobs/sha256:9e557bdec7d1561d0553244d6aa08a4f152c6d6656c780009e85e8591d81a1af"
level=debug msg="GET https://registry-1.docker.io/v2/library/ubuntu/blobs/sha256:9e557bdec7d1561d0553244d6aa08a4f152c6d6656c780009e85e8591d81a1af"
Copying blob sha256:de21e52cfb21f634ab48959716b6f989328d5324043d6a259ca15df8a04e7f8d
level=debug msg="Detected compression format gzip"
level=debug msg="Using original blob without modification"
Copying blob sha256:9e557bdec7d1561d0553244d6aa08a4f152c6d6656c780009e85e8591d81a1af
level=debug msg="Detected compression format gzip"
level=debug msg="Using original blob without modification"
Copying blob sha256:8f57cefb68887255bfffe7e6ddee55ac93c131dc9ceedf6bbf1dfec7836abe75
level=debug msg="Detected compression format gzip"
level=debug msg="Using original blob without modification"
Copying config sha256:bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c
level=debug msg="No compression detected"
level=debug msg="Using original blob without modification"
Writing manifest to image destination
Storing signatures
level=debug msg="Start untar layer"
level=debug msg="Untar time: 0.979557124s"
level=debug msg="Start untar layer"
level=debug msg="Untar time: 0.150728266s"
level=debug msg="Start untar layer"
level=debug msg="Untar time: 0.131257725s"
level=debug msg="setting image creation date to 2021-03-04 02:24:57.603616158 +0000 UTC"
level=debug msg="created new image ID \"bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\""
level=debug msg="set names of image \"bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\" to [docker.io/library/ubuntu:20.10]"
level=debug msg="saved image metadata \"{\\\"signatures-sizes\\\":{\\\"sha256:b10694fc29f6c511a7e8b7c1a7e3330c91c6c7addf2cc3b9627413c4a19d261f\\\":[]}}\""
level=debug msg="exporting opaque data as blob \"sha256:bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\""
level=debug msg="Container ID: c0e92e6968e8fd811f193119397e306f7aaed66d7aaa634327e9e40f496b74fc"
level=debug msg="COMMIT example/ubuntu:latest"
STEP 2: COMMIT example/ubuntu:latest
level=debug msg="parsed reference into \"[vfs@/var/lib/containers/storage+/run/containers/storage]localhost/example/ubuntu:latest\""
level=debug msg="parsed reference into \"[vfs@/var/lib/containers/storage+/run/containers/storage]@bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\""
level=debug msg="Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb"
level=debug msg="IsRunningImageAllowed for image containers-storage:[vfs@/var/lib/containers/storage]@bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c"
level=debug msg=" Using default policy section"
level=debug msg=" Requirement 0: allowed"
level=debug msg="Overall: allowed"
level=debug msg="exporting opaque data as blob \"sha256:bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\""
level=debug msg="Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json]"
level=debug msg="... will first try using the original manifest unmodified"
level=debug msg="Skipping blob sha256:67b801d22d3f5eba2e24c6049c7bb7e2cfb8b4dca2788bab5b1914b89e1d64e2 (already present):"
level=debug msg="Skipping blob sha256:dfd839447483acf154c960f604255ff61780be3d9d5f9c95d326164ebe8beb69 (already present):"
level=debug msg="Skipping blob sha256:7296e683f87460d366c186b86fcb007542705e10560bbc0a6a78689ee2bacca0 (already present):"
level=debug msg="No compression detected"
level=debug msg="Using original blob without modification"
level=debug msg="setting image creation date to 2021-03-04 02:24:57.603616158 +0000 UTC"
level=debug msg="reusing image ID \"bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\""
level=debug msg="set names of image \"bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\" to [localhost/example/ubuntu:latest docker.io/library/ubuntu:20.10]"
level=debug msg="saved image metadata \"{\\\"signatures-sizes\\\":{\\\"sha256:e2e658a00150ebbe654a4a311ae751a582a0a38353b8aa9b6514f2e7e7b0adad\\\":[]}}\""
--> bbd39996e8f
level=debug msg="printing final image id \"bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c\""
level=debug msg="shutting down the store"
bbd39996e8ff6b7585d7bf15f1bf54826a3a615521c5f2ad814eb03182dc532c
+ buildah images --all
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
+ buildah push --authfile /root/destination-auth example/ubuntu:latest docker://docker.io/example/ubuntu:latest
error pushing image "example/ubuntu:latest" to "docker://docker.io/example/ubuntu:latest": error locating image with name "example/ubuntu:latest" ([localhost/example/ubuntu:latest registry.fedoraproject.org/example/ubuntu:latest registry.access.redhat.com/example/ubuntu:latest registry.centos.org/example/ubuntu:latest docker.io/example/ubuntu:latest]): image not known
level=error msg="exit status 125"
```
