### ISSUE TITLE
regression? pipe into buildah run stopped working

### ISSUE THREAD

**Issue by ppenguin** [containers/buildah#3246]
This script used to work before:

```bash
podman pull docker.io/frolvlad/alpine-glibc
C=$(buildah from frolvlad/alpine-glibc)
# copy shlibs
TDIR="/opt/shlibs"
BAA="shlibs.tgz"
cat ${BAA} | buildah run -t $C /bin/sh -c '[[ -d '"${TDIR}"' ]] || mkdir -p '"${TDIR}"'; /bin/tar -C '"${TDIR}"' -zxf -; echo "Done."'
```

but apparently stopped working since a recent update

**Steps to reproduce the issue:**

Simplified form also doesn't work:

```
❯ podman pull docker.io/frolvlad/alpine-glibc
❯ C=$(buildah from frolvlad/alpine-glibc)
❯ echo "Hello" | buildah run -t $C /bin/sh -c 'cat -'
Hello
Hello
# and now hangs instead of returning after EOF
```

**Describe the results you received:**

see above

**Describe the results you expected:**

Print "Hello" and exit.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
❯ pamac list -i  | grep buildah
buildah                                   1.20.1-1                              community  27.5 MB
```

**Output of `buildah version`:**

```bash
❯ buildah --version
buildah version 1.20.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
❯ cat /etc/*release
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.5
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**Output of `uname -a`:**

```
Linux jmanji 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```toml
❯ cat /etc/containers/storage.conf | grep -oE '^[^#].*'
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"
mountopt = "nodev"
[storage.options.thinpool]
ostree_repo = ""
skip_mount_home = "false"
```

It looks similar to [this issue](https://github.com/containers/buildah/issues/1650) but I never encountered it before since using this script (approx a few months, mostly on current `buildah` version)
