### ISSUE TITLE
Buildah in Tekton task is failing with: unshare(CLONE_NEWUSER): Invalid argument

### ISSUE THREAD

**Issue by cgruver** [containers/buildah#3455]
buildah version: multiple (1.16, 1.21, 1.22)

Tekton Pipelines version 1.22 (OpenShift Pipelines 1.4.1)

We have observed three OpenShift clusters where buildah starts failing with the following errors:

```bash
unshare(CLONE_NEWUSER): Invalid argument
ERRO error parsing PID "": strconv.Atoi: parsing "": invalid syntax
ERRO (unable to determine exit status)
```

Once it starts failing, it always fails.  We don't believe that the issue is directly related to buildah, but hope that someone might have a clue.  It's almost like underlying permissions are being affected for the pipeline service account running with the pipeline-scc SecurityContextConstraint.

The following Tekton `Task` works on the other clusters.  It fails with the above error in the clusters where the issue has manifested itself.

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-test
spec:
  stepTemplate:
    volumeMounts:
    - name: varlibc
      mountPath: /var/lib/containers
  steps:
  - name: prep-workingdir
    image: quay.io/buildah/stable:latest
    imagePullPolicy: IfNotPresent
    script: |
      chmod 777 /workspace/source
      cp -r /tekton/creds/.docker /workspace/source
      chown -R 1000:1000 /workspace/source/.docker
    env:
    - name: user.home
      value: /workspace/source
    workingDir: "/workspace/source"
  - name: build-image
    image: quay.io/buildah/stable:latest
    securityContext:
      runAsUser: 1000
    imagePullPolicy: IfNotPresent
    script: |
      export HOME=/workspace/source
      export BUILDAH_ISOLATION=chroot
      APP_NAME=test
      DESTINATION_IMAGE="image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/${APP_NAME}:latest"
      buildah --version
      BUILDAH_ARGS="--storage-driver vfs"
      CONTAINER=$(buildah ${BUILDAH_ARGS} from quay.io/buildah/stable:latest )
      # CONTAINER=$(buildah --storage-driver vfs --log-level trace --userns-uid-map $(id -u):$(( $(id -u) + 1 )):65536 --userns-gid-map $(id -u):$(( $(id -u) + 1 )):65536 --tls-verify=false from quay.io/buildah/stable:latest )
      cat << EOF > ./test.sh
      #!/bin/bash
      echo "hello"
      EOF
      chmod 750 ./test.sh
      buildah ${BUILDAH_ARGS} copy ${CONTAINER} ./test.sh /application.sh
      buildah ${BUILDAH_ARGS} config --entrypoint '["/application.sh"]' --port 8080 ${CONTAINER}
      buildah ${BUILDAH_ARGS} config --label GIT_COMMIT="Hello" --author="Tekton" ${CONTAINER}
      buildah ${BUILDAH_ARGS} commit ${CONTAINER} ${DESTINATION_IMAGE}
      buildah ${BUILDAH_ARGS} unmount ${CONTAINER}
      buildah ${BUILDAH_ARGS} push ${DESTINATION_IMAGE} docker://${DESTINATION_IMAGE}
    env:
    - name: user.home
      value: /workspace/source
    workingDir: "/workspace/source"
  volumes:
  - name: varlibc
    emptyDir: {}
```

I posted this on the Tekton Operator project as well.

https://github.com/tektoncd/operator/issues/381

**Comment by rhatdan** [comment]
Could you check to see if there are seccomp or selinux avc errors in the audit.log when this fails.

ausearch -m seccomp
ausearch -m avc

Could this be an older kernel?

@giuseppe WDYT?

**Comment by cgruver** [comment]
We pinned a pod to a specific node and monitored both `journalctl` and `/var/log/audit/audit.log`

We didn't see anything.  But in the morning we'll look specifically for seccomp and avc.

This base OS is RHCOS on OCP 4.7.9 and ROSA 4.7.19

**Comment by cgruver** [comment]
No output from either of:

```bash
ausearch -m seccomp
ausearch -m avc
```

Kernel info: `Linux ip-10-112-120-43 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Mar 25 14:36:04 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`

Additional trace level output:

```bash
running [buildah-in-a-user-namespace --log-level trace from scratch]

container=oci STORAGE_DRIVER=vfs _BUILDAH_STARTED_IN_USERNS= BUILDAH_ISOLATION=chroot HOME=/root TMPDIR=/var/tmp _CONTAINERS_USERNS_CONFIGURED=1], UID map [{ContainerID:0 HostID:0 Size:4294967295}], and GID map [{ContainerID:0 HostID:0 Size:4294967295}]"
```

Here is a much simpler test to reproduce.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: buildah-bare-test
spec:
  serviceAccountName: pipeline
  restartPolicy: Never
  containers:
    - name: buildah
      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      command: ["buildah", "from", "scratch"]
      volumeMounts:
      - mountPath: /var/lib/containers
        name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
```

Same error output:

```bash
Error during unshare(CLONE_NEWUSER): Invalid argument
level=error msg="error parsing PID \"\": strconv.Atoi: parsing \"\": invalid syntax"
level=error msg="(unable to determine exit status)"
```
