### ISSUE TITLE
runtime/cgo: pthread_create failed since upgrade to buildah 1.23 when used in gitlab-ci job

### ISSUE THREAD

**Issue by rtheys** [containers/buildah#3643]
Hi,

We use buildah in a Gitlab CI file to build a container image. This has worked fine for a long time, but since the upgrade to buildah 1.23, this fails with the following error:

```
Using docker image sha256:2f9e170327fd5720ff634553f62f2acf4ad2d80550f35459bc712a8b4bfdf27c for quay.io/buildah/stable with digest quay.io/buildah/stable@sha256:a569b777ea9bc97ef16b44d3252ad038ba15533e138ff7446055709bda81b7ba ...
$ export REGISTRY_AUTH_FILE=${HOME}/auth.json
$ echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f6b961b985c m=0 sigcode=18446744073709551610
goroutine 0 [idle]:
runtime: unknown pc 0x7f6b961b985c
stack: frame={sp:0x7ffc6b3073f0, fp:0x0} stack=[0x7ffc6ab08950,0x7ffc6b307990)
00007ffc6b3072f0:  0000000000000000  00007ffc6b307338 
00007ffc6b307300:  0000557c9f8437ba <runtime.mmap.func1+90>  00007f6b8175f000 
00007ffc6b307310:  0000000000001000  0000003200000003 
00007ffc6b307320:  00000000ffffffff  00007f6b8175f000 
00007ffc6b307330:  00007ffc6b307378  00007ffc6b3073b0 
00007ffc6b307340:  0000557c9f7e23de <runtime.mmap+158>  00007ffc6b307380 
00007ffc6b307350:  00007ffc6b3073a0  0000557c9f7f8805 <runtime.sysAlloc+261> 
00007ffc6b307360:  0000557ca0f017f8  00007ffc6b307390 
00007ffc6b307370:  00007ffc6b3073a0  0000557ca03cb800 
00007ffc6b307380:  0000557c9f843760 <runtime.mmap.func1+0>  00007ffc6b3073b0 
00007ffc6b307390:  00007ffc6b3073c0  0000557ca03cb800 
00007ffc6b3073a0:  00007f6b961b4ef0  000000001c000004 
00007ffc6b3073b0:  00007f6b9616c760  00007f6b961c6e59 
00007ffc6b3073c0:  0000000000000000  0000000000000014 
00007ffc6b3073d0:  0000000000000160  0000000000000000 
00007ffc6b3073e0:  0000000000000150  00007f6b961b984e 
00007ffc6b3073f0: <0000000000000016  0000000000000400 
00007ffc6b307400:  0000000000000000  0000000000000005 
00007ffc6b307410:  0000003500000016  00007f6b9623c711 
00007ffc6b307420:  00007f6b6f2ad640  00007ffc6b307700 
00007ffc6b307430:  00007ffc6b30755e  00007ffc6b30755f 
00007ffc6b307440:  00007f6b6f2ad640  00007f6b961b7785 
00007ffc6b307450:  00007f6b96324aa0  0000000000000150 
00007ffc6b307460:  00000000003d0f00  00007f6b6f2ad910 
00007ffc6b307470:  00007f6b6f2ad910  bf840e0d2b506600 
00007ffc6b307480:  00007f6b95f3f840  0000000000000006 
00007ffc6b307490:  0000557ca055ef3e  00007ffc6b3077c0 
00007ffc6b3074a0:  0000557ca0546750  00007f6b9616c6b6 
00007ffc6b3074b0:  00007f6b96326990  00007f6b961567d3 
00007ffc6b3074c0:  0000000000000020  00007f6b6f2ad640 
00007ffc6b3074d0:  0000000000000000  0000000000000001 
00007ffc6b3074e0:  00007f6b6f2ad640  00007f6b961b855c 
runtime: unknown pc 0x7f6b961b985c
stack: frame={sp:0x7ffc6b3073f0, fp:0x0} stack=[0x7ffc6ab08950,0x7ffc6b307990)
00007ffc6b3072f0:  0000000000000000  00007ffc6b307338 
00007ffc6b307300:  0000557c9f8437ba <runtime.mmap.func1+90>  00007f6b8175f000 
00007ffc6b307310:  0000000000001000  0000003200000003 
00007ffc6b307320:  00000000ffffffff  00007f6b8175f000 
00007ffc6b307330:  00007ffc6b307378  00007ffc6b3073b0 
00007ffc6b307340:  0000557c9f7e23de <runtime.mmap+158>  00007ffc6b307380 
00007ffc6b307350:  00007ffc6b3073a0  0000557c9f7f8805 <runtime.sysAlloc+261> 
00007ffc6b307360:  0000557ca0f017f8  00007ffc6b307390 
00007ffc6b307370:  00007ffc6b3073a0  0000557ca03cb800 
00007ffc6b307380:  0000557c9f843760 <runtime.mmap.func1+0>  00007ffc6b3073b0 
00007ffc6b307390:  00007ffc6b3073c0  0000557ca03cb800 
00007ffc6b3073a0:  00007f6b961b4ef0  000000001c000004 
00007ffc6b3073b0:  00007f6b9616c760  00007f6b961c6e59 
00007ffc6b3073c0:  0000000000000000  0000000000000014 
00007ffc6b3073d0:  0000000000000160  0000000000000000 
00007ffc6b3073e0:  0000000000000150  00007f6b961b984e 
00007ffc6b3073f0: <0000000000000016  0000000000000400 
00007ffc6b307400:  0000000000000000  0000000000000005 
00007ffc6b307410:  0000003500000016  00007f6b9623c711 
00007ffc6b307420:  00007f6b6f2ad640  00007ffc6b307700 
00007ffc6b307430:  00007ffc6b30755e  00007ffc6b30755f 
00007ffc6b307440:  00007f6b6f2ad640  00007f6b961b7785 
00007ffc6b307450:  00007f6b96324aa0  0000000000000150 
00007ffc6b307460:  00000000003d0f00  00007f6b6f2ad910 
00007ffc6b307470:  00007f6b6f2ad910  bf840e0d2b506600 
00007ffc6b307480:  00007f6b95f3f840  0000000000000006 
00007ffc6b307490:  0000557ca055ef3e  00007ffc6b3077c0 
00007ffc6b3074a0:  0000557ca0546750  00007f6b9616c6b6 
00007ffc6b3074b0:  00007f6b96326990  00007f6b961567d3 
00007ffc6b3074c0:  0000000000000020  00007f6b6f2ad640 
00007ffc6b3074d0:  0000000000000000  0000000000000001 
00007ffc6b3074e0:  00007f6b6f2ad640  00007f6b961b855c 
goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/golang/src/runtime/asm_amd64.s:339 fp=0xc00005c788 sp=0xc00005c780 pc=0x557c9f84dc40
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:144 +0x8d fp=0xc00005c7e0 sp=0xc00005c788 pc=0x557c9f819aed
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x557c9f84fa81
rax    0x0
rbx    0x7f6b95f3f840
rcx    0xffffffffffffffff
rdx    0x6
rdi    0xa
rsi    0xa
rbp    0xa
rsp    0x7ffc6b3073f0
r8     0x7ffc6b3074c0
r9     0x7f6b962e04e0
r10    0x8
r11    0x246
r12    0x6
r13    0x7ffc6b3077c0
r14    0x557ca0546750
r15    0x0
rip    0x7f6b961b985c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Cleaning up project directory and file based variables
```

If I change the gitlab CI file to use buildah v1.22.3 again, it works fine again.

**Steps to reproduce the issue:**
1. Create a gitlab ci file to use buildah, for example:
```
---
stages:
  - bug

image:
  name: quay.io/buildah/stable
  entrypoint: ['/bin/sh', '-c']

container_bug:
  stage: bug
  variables:
    IMAGE_NAME: "my-image-name"
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "docker"
  script:
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "The CI_REGISTRY_IMAGE is set to ${CI_REGISTRY_IMAGE}"
    - echo "The CI_COMMIT_REF_SLUG is ${CI_COMMIT_REF_SLUG}"
    - echo "The CI_COMMIT_SHORT_SHA is ${CI_COMMIT_SHORT_SHA}"
    - export OURTAG="${CI_COMMIT_SHORT_SHA}_$(date +%Y%m%d%H%M)"
    - echo "OURTAG = ${OURTAG}"
    - buildah bud --squash -f Containerfile -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${OURTAG} -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest .
    - buildah push ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${OURTAG}
    - buildah push ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest
    - buildah logout ${CI_REGISTRY}
```
2. Run the pipeline
3.

**Describe the results you received:**
Fails with the message above

**Describe the results you expected:**
Builds as before with buildah 1.22.3

**Output of `cat /etc/*release`:**

The gitlab runner host is running CentOS 7 with docker.
