### ISSUE TITLE
Build image : operation not permitted

### ISSUE THREAD

**Issue by Mathie01** [containers/buildah#4538]
**Description**

With this Dockerfile :

```
FROM docker.io/nginx:1.23.3-alpine

RUN apk add --update --no-cache nodejs npm libc6-compat
```

I get the following error:

```
STEP 2/14: RUN apk add --update --no-cache nodejs npm libc6-compat
error running subprocess: creating new mount namespace for [/bin/sh -c apk add --update --no-cache nodejs npm libc6-compat]: operation not permitted
Error: building at STEP "RUN apk add --update --no-cache nodejs npm libc6-compat": exit status 1
```

**Steps to reproduce the issue:**
1. Get the above Dockerfile
2. Use buildah build command

**Describe the results you received:**

I get the following error:

```
STEP 2/14: RUN apk add --update --no-cache nodejs npm libc6-compat
error running subprocess: creating new mount namespace for [/bin/sh -c apk add --update --no-cache nodejs npm libc6-compat]: operation not permitted
Error: building at STEP "RUN apk add --update --no-cache nodejs npm libc6-compat": exit status 1
```

**Describe the results you expected:**

I am waiting for the image to build

**Output of `rpm -q buildah` or `apt list buildah`:**

I can't, I use Gitlab CI / CD for this

**Output of `buildah version`:**

I use Gitlab CI / CD with buildah image
```
v1.28
```

My Gitlab CI / CD configuration : 

```
docker_build:
  stage: docker_build
  image: quay.io/buildah/stable:v1.28
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: vfs
    # Write all image metadata in the docker format, not the standard OCI format.
    # Newer versions of docker can handle the OCI format, but older versions, like
    # the one shipped with Fedora 30, cannot handle the format.
    BUILDAH_FORMAT: docker
    # You may need this workaround for some errors: https://stackoverflow.com/a/70438141/1233435
    BUILDAH_ISOLATION: chroot
  before_script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildah build -t frontend:$CI_COMMIT_SHA -f Dockerfile.dashboard
    - buildah push frontend:$CI_COMMIT_TAG

```

**Comment by rhatdan** [comment]
Could you try with --isolation=chroot?

**Comment by Mathie01** [comment]
Hello !

Same thing :

![image](https://user-images.githubusercontent.com/67562521/214105863-dae5cdbe-7462-4cd9-921b-5d61c7d41a51.png)

**Comment by rhatdan** [comment]
It looks like you are running buildah within a confined environment, while docker is probably leaking the docker.sock into the container and using it.

**Comment by Mathie01** [comment]
I can't find any information on the Internet: it seems that nobody builds his image with Gitlab and Buildah

**Comment by MartinX3** [comment]
I've got the same problem.
We use buildah as build agent in jenkins in kubernetes and since 1.28 I can't use anymore `RUN addgroup -g 1001 -S appuser` in the dockerfile to build the image
`error running subprocess: creating new mount namespace for [/bin/sh -c addgroup -g 1001 -S appuser]: operation not permitted`

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by slonopotamus** [comment]
Experiencing the same issue. Unable to `RUN` anything when running buildah v1.28.0 inside Docker container:

```
error running subprocess: creating new mount namespace for [/bin/sh -c dotnet tool install -g dotnet-trace]: operation not permitted
Error: building at STEP "RUN dotnet tool install -g dotnet-trace": exit status 1
```

Note that neither 1.28.3 nor 1.29.0 are available via https://quay.io/repository/buildah/stable so I am not sure how to test them.

**Comment by flouthoc** [comment]
I think issue is more with the version `v1.28.0`, I'd request to bump buildah version please see comment here: https://github.com/containers/buildah/issues/4553#issuecomment-1413694479

**Comment by flouthoc** [comment]
@slonopotamus Please try with `quay.io/buildah/upstream:latest`

**Comment by slonopotamus** [comment]
`quay.io/buildah/upstream:latest` fails in a much worse way:

```
Error during unshare(CLONE_NEWUSER): Operation not permitted
ERRO[0000] parsing PID "": strconv.Atoi: parsing "": invalid syntax 
ERRO[0000] (Unable to determine exit status)
```

Note that this happens even with `--isolation=chroot`. I'm using Docker 20.10.22.

**Comment by flouthoc** [comment]
@slonopotamus Could you try 
```console
[fl@fedora ~]$ sudo docker run --privileged --user 1000 --rm -it quay.io/buildah/upstream:latest buildah unshare echo hi
```

**Comment by slonopotamus** [comment]
It works both with and without `sudo`.

```
$ docker run --privileged --user 1000 --rm -it quay.io/buildah/upstream:latest buildah unshare echo hi
hi

$ su -c "docker run --privileged --user 1000 --rm -it quay.io/buildah/upstream:latest buildah unshare echo hi"
Password: 
hi
```

Obviously, this is not a way to go due because of security reasons.

**Comment by slonopotamus** [comment]
So, I'm not sure we're talking about a _single_ issue here. I see that 1.28.0 works _better_ than 1.27.0 or 1.29.0 in some aspect (only 1.28.0 passes `buildah unshare echo hi` inside Docker). But even 1.28.0 fails to `RUN` anything in Dockerfile.

**Comment by slonopotamus** [comment]
Okay, I know why `buildah unshare echo hi` works in 1.28.0 and doesn't work on 1.29.0 (and `main` branch). It was broken by https://github.com/containers/storage/commit/1af3928e9bf16d9c39d3d60bf3ec6bb7167989a6.

**Comment by giuseppe** [comment]
how were you able to run nested containers without CAP_SYS_ADMIN and without the possibility to create a new user namespace?  Were you using `buildah run`?

**Comment by slonopotamus** [comment]
I'm not able to _run_ nested containers, that's the whole point of current issue.

But before https://github.com/containers/storage/pull/1415 landed to buildah, I was able to _build_ containers from Dockerfile. `COPY` files, use `FROM` stages, etc. And now buildah just exists immediately.

**Comment by giuseppe** [comment]
you either need to add CAP_SYS_ADMIN or customize the seccomp profile to allow the `unshare` syscall

**Comment by slonopotamus** [comment]
I fail to understand why I need that to run `buildah info`, for example.

**Comment by giuseppe** [comment]
I think we don't need it for `buildah info` and we could list the commands that do not need a new user namespace, as we do for Podman

**Comment by slonopotamus** [comment]
Okay, let's return to the original issue. Is `CAP_SYS_ADMIN` or `unshare(CLONE_NEWUSER)` by design a **hard** requirement for buildah in order to be able to `RUN` things from `Dockerfile`, even with `--isolation=chroot`? And this means that buildah cannot `RUN` things with default Docker settings in unprivileged container?

**Comment by slonopotamus** [comment]
https://github.com/containers/buildah/issues/1901#issuecomment-539499449 claims that `--isolation=chroot` "eliminates the `unshare` call", but this is not what we observe. https://github.com/containers/buildah/issues/4538#issuecomment-1400698405 also suggest `--isolation=chroot` as a way to avoid `unshare`.

So, I cannot understand whether it is by design that buildah doesn't work at all without `unshare` or it is just a bug and there should be some scenarios where buildah is usable even without `CAP_SYS_ADMIN`/`unshare(CLONE_NEWUSER)`.

**Comment by giuseppe** [comment]
`--isolation=chroot` uses the mount syscall, for that to work there is need to have `CAP_SYS_ADMIN` in the current user namespace and own the mount namespace.

You still need `CAP_SYS_ADMIN` or be able to create a user namespace with the `unshare` syscall.

**Comment by slonopotamus** [comment]
To my understanding, `CAP_SYS_ADMIN` is much less secure than `unshare(CLONE_NEWUSER)` and gives container lots of control over host machine. And even `unshare(CLONE_NEWUSER)` is the source of various CVEs, that's why it is disabled in Docker by default.

**Comment by slonopotamus** [comment]
> I think we don't need it for `buildah info` and we could list the commands that do not need a new user namespace, as we do for Podman

I've created a separate issue for this, since we're talking about something that worked before and now doesn't: https://github.com/containers/buildah/issues/4563

**Comment by mick1627** [comment]
Here my Kubernetes configuration that works on anthos gke in AWS, if it can help. Build is done in gitlab ci with a kubernetes executor. 
I run buildah with user 1000 (BUILDAH_ISOLATION: chroot). What was not really clear for me is that even if it run in rootless mode, allowPrivilegeEscalation must be set to true to allow the usage of SETGID/SETUID. Adding capabilities have no effect if  allowPrivilegeEscalation is set to false.

Here the securityContext needed for the pod where buildah is running:


```yaml
     securityContext:
        capabilities:
          add:
            - SETGID
            - SETUID
          drop:
            - ALL
        privileged: false
        runAsUser: 1000
        allowPrivilegeEscalation: true
```

I drop all capabilities to only allow SETGID and SETUID

I also need to set this annotation otherwise apparmor blocks the usage of setgid
```yaml
  annotations:
    container.apparmor.security.beta.kubernetes.io/build: unconfined
```

and last my .gitlab-ci.yml


```yaml
image: 
  name: quay.io/buildah/stable:v1.28
  #name: quay.io/buildah/upstream:latest

variables:
  HTTP_PROXY: $HTTP_PROXY
  HTTPS_PROXY: $HTTPS_PROXY
  NO_PROXY: $NO_PROXY
  # Use vfs with buildah. Docker offers overlayfs as a default, but buildah
  # cannot stack overlayfs on top of another overlayfs filesystem.
  #STORAGE_DRIVER: vfs
  # Write all image metadata in the docker format, not the standard OCI format.
  # Newer versions of docker can handle the OCI format, but older versions, like
  # the one shipped with Fedora 30, cannot handle the format.
  BUILDAH_FORMAT: docker
  # You may need this workaround for some errors: https://stackoverflow.com/a/70438141/1233435
  BUILDAH_ISOLATION: chroot


master:
  stage: build
  only:
    - master
  script:
    - id
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah build --build-arg http_proxy=${HTTP_PROXY} --build-arg https_proxy=${HTTPS_PROXY} --build-arg no_proxy=${NO_PROXY} -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f $CI_PROJECT_DIR/Dockerfile
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  tags:
    - k8s
```
