### ISSUE TITLE
`build`: Change of `--secret` does not trigger layer rebuild

### ISSUE THREAD

**Issue by rijenkii** [containers/buildah#4822]
**Description**

When building a `Containerfile` that uses secrets with flag `--layers` set, change of secret does not trigger rebuild of a layer.

**Steps to reproduce the issue:**
1. Create `Containerfile` with contents:
   ```Containerfile
   FROM docker://docker.io/debian:11-slim
   RUN --mount=type=secret,id=secret cp /run/secrets/secret /
   ```
3. ```bash
   buildah build --layers --secret id=secret,src=<(echo "123") -f Containerfile .
   ```
4. ```bash
   buildah build --layers --secret id=secret,src=<(echo "321") -f Containerfile .
   ```

**Describe the results you received:**

First build pulled the debian image from dockerhub and built all layers:
```
STEP 1/2: FROM docker://docker.io/debian:11-slim
Trying to pull docker.io/library/debian:11-slim...
Getting image source signatures
Copying blob f03b40093957 done  
Copying config f8e203ddac done  
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN --mount=type=secret,id=secret cp /run/secrets/secret /
COMMIT
--> b35e83b96c7b
b35e83b96c7b91863104d44e7d50e7acee99589e4a693cfbcf8e9a2b3d30e442
```

Second build used cached layers for all steps:
```
STEP 1/2: FROM docker://docker.io/debian:11-slim
STEP 2/2: RUN --mount=type=secret,id=secret cp /run/secrets/secret /
--> Using cache b35e83b96c7b91863104d44e7d50e7acee99589e4a693cfbcf8e9a2b3d30e442
--> b35e83b96c7b
b35e83b96c7b91863104d44e7d50e7acee99589e4a693cfbcf8e9a2b3d30e442
```

**Describe the results you expected:**

Second step would be rebuilt, because contents of `/run/secrets/secret` file are changed.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ pacman -Q buildah
buildah 1.30.0-1
```

**Output of `buildah version`:**

```
Version:         1.30.0
Go Version:      go1.20.3
Image Spec:      1.0.2-dev
Runtime Spec:    1.1.0-rc.1
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.25.0
Git Commit:      04965f1198104afafd22197a479bd15c9b43148e
Built:           Wed Apr 19 10:50:43 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
Arch Linux releaseDISTRIB_ID="Artix"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Artix Linux"
NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo
```

**Output of `uname -a`:**

```
Linux RijenkiiBook 6.3.1-artix1-1 #1 SMP PREEMPT_DYNAMIC Thu, 04 May 2023 01:47:06 +0000 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```toml
# comments removed
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = []
pull_options = {enable_partial_images = "false", use_hard_links = "false", ostree_repos=""}
[storage.options.overlay]
mountopt = "nodev"
[storage.options.thinpool]
```
