### ISSUE TITLE
do we need to run buildah containers always with BUILDAH_ISOLATION = chroot

### ISSUE THREAD

**Issue by himmatss** [containers/buildah#5818]
Hi,

I have a buildah container image (quay.io/buildah/stable:latest) running with default setting as a "BUILDAH_ISOLATION = chroot"  in Kubernetes. However, I am wondering is this really required to run the buildah as a container ? 

Can someone pleas explain this ,
https://github.com/containers/buildah/blob/main/docs/buildah-build.1.md
_"--isolation type

Controls what type of isolation is used for running processes as part of RUN instructions. Recognized types include oci (OCI-compatible runtime, the default), rootless (OCI-compatible runtime invoked using a modified configuration, with --no-new-keyring added to its create invocation, reusing the host's network and UTS namespaces, and creating private IPC, PID, mount, and user namespaces; the default for unprivileged users), and chroot (an internal wrapper that leans more toward chroot(1) than container technology, reusing the host's control group, network, IPC, and PID namespaces, and creating private mount and UTS namespaces, and creating user namespaces only when they're required for ID mapping).

Note: You can also override the default isolation type by setting the BUILDAH_ISOLATION environment variable. export BUILDAH_ISOLATION=oci"_

**Comment by nalind** [comment]
In many cases, a container that's run using the image will not be given enough privileges for `buildah run` or the handling of RUN instructions in Dockerfiles in `buildah build` to be able to launch a container using an actual runtime like crun or runc.  The chroot-based method is severely limited in functionality compared to crun or runc, but in return it exercises fewer privileges than they might, so it works (or "works") in a number of cases where they might not.  If your environment provides enough privileges to not have to use chroot, feel free to override it.

**Comment by himmatss** [comment]
Thanks @nalind for your reply. 
The documentation says the default value is "oci" for the BUILDAH_ISOLATION but in the dockerfile of the image quay.io/buildah/stable:latest ; it appears to be having the BUILDAH_ISOLATION=chroot
https://github.com/containers/image_build/blob/main/podman/Containerfile
https://github.com/containers/image_build/blob/main/buildah/Containerfile

**Comment by nalind** [comment]
Yes, the container image has the environment variable set in it to override the compiled-in default.

**Comment by chmeliik** [comment]
I have a similar need to run buildah in Kubernetes with better isolation.

> If your environment provides enough privileges to not have to use chroot, feel free to override it.

What privileges are those? How can I check if the environment provides them?

**Comment by chmeliik** [comment]
I've had some time to play with it. I ended up with a Pod definition that seemingly makes nested containerization possible with `BUILDAH_ISOLATION=oci`

<details>
<summary>buildah-pod.yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: buildah-
  labels:
    buildah-isolation-test: "true"
  annotations:
    # /dev/fuse fixes:
    #
    # fuse: device not found, try 'modprobe fuse' first
    #
    # Wouldn't be needed with STORAGE_DRIVER=vfs
    io.kubernetes.cri-o.Devices: /dev/fuse
spec:
  restartPolicy: Never
  volumes:
     - name: workdir
       emptyDir: {}

  initContainers:
    - name: create-dockerfile
      image: quay.io/containers/buildah:v1.38.1
      volumeMounts:
        - name: workdir
          mountPath: /workdir
      workingDir: /workdir
      command: ["bash", "-c"]
      args:
        - |-
          cat << EOF > Dockerfile
          FROM docker.io/library/alpine:latest

          RUN echo "hello world"
          EOF

  containers:
    - name: buildah
      image: quay.io/containers/buildah:v1.38.1
      volumeMounts:
        - name: workdir
          mountPath: /workdir
      workingDir: /workdir
      env:
        - name: BUILDAH_ISOLATION
          value: oci
        - name: STORAGE_DRIVER
          value: overlay
      command: ["bash", "-c"]
      # unshare fixes:
      #
      # error running container: from /usr/bin/crun ... opening file `/sys/fs/cgroup/cgroup.subtree_control` for writing: Read-only file system
      #
      # --mount fixes:
      #
      # Error: mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: operation not permitted
      #
      # --map-root-user fixes:
      #
      # unshare: unshare failed: Operation not permitted

      # --net=host fixes:
      #
      # error running container: from /usr/bin/crun ...: open `/proc/sys/net/ipv4/ping_group_range`: Read-only file system
      #
      # --pid=host fixes:
      #
      # error running container: from /usr/bin/crun ...: mount `proc` to `proc`: Operation not permitted
      args:
        - |-
          # can also add --pid --fork to unshare
          unshare --map-root-user --mount -- buildah build --net=host --pid=host .
      securityContext:
        capabilities:
          add:
            # SETFCAP fixes:
            #
            # unshare: write failed /proc/self/uid_map: Operation not permitted
            - SETFCAP
        seLinuxOptions:
          # container_runtime_t fixes:
          #
          # error running container: from /usr/bin/crun ...: mount `devpts` to `dev/pts`: Permission denied
          type: container_runtime_t
```

</details>

@nalind could you share your thoughts on the security implications of the settings I had to use:
* `--net=host --pid=host` for buildah
  * You mentioned `--net=host` would be OK to use, does the same apply for `--pid=host`?
  * Could also be combined with `unshare --pid --fork`, which may help mitigate potential implications of `--pid=host`?
* `SETFCAP` for the pod to enable `unshare --map-root-user`
* `container_runtime_t` SELinux label for the pod to get around ``mount `devpts` to `dev/pts`: Permission denied`` from crun
