### ISSUE TITLE
[feature request] add options to specify where layers are stored localy

### ISSUE THREAD

**Issue by mcarbonneaux** [containers/buildah#5899]
in issue "https://github.com/containers/buildah/issues/4638" we see echange about the imposibility to specify local localtion of the layers with "--cache-to" and "--cache-from"...

in ci/cd in general you can cache ([gitlab cache](https://docs.gitlab.com/ee/ci/caching/#cache)) in the pipe line between jobs execution, but you need to kown where the data are stored and many build tool had option to specify where cache file are stored.

can you add the posibility to specify the local location with `--cache-to` and `--cache-from` ?

and at minima where the default location of the layers ?

**Comment by flouthoc** [comment]
I think we were working on something similar at one point https://github.com/containers/buildah/pull/4879 ( not sure if that is what you need ).

But buildah also allows you to manually configure `runroot` and `graphroot`  the paths which buildah uses from all the persistent storage. I would suggest taking a look at `storage.conf`.

**Comment by mcarbonneaux** [comment]
https://github.com/containers/buildah/pull/4879 seem to match what i say !

but you've right about runroot and graphroot and stroage.conf i think... i while go to try that! 

https://github.com/containers/podman/blob/main/vendor/github.com/containers/storage/storage.conf

**Comment by sebhoss** [comment]
We declare a volume in our GitLab runners which we use as a persistent cache across projects/jobs like this:

```toml
  [runners.docker]
    ...
    privileged = false
    volumes = ["/cache"]
```

In our build jobs we specify  `--root` and `--runroot` while calling `buildah build` like this:

```yaml
build-job:
  image: quay.io/buildah/stable:latest
  script:
    - buildah build
      --root /cache/buildah/root
      --runroot /cache/buildah/runroot
      --tag ...
```

This seems to work fine as we are seeing that buildah uses our shared cache.
