### ISSUE TITLE
"buildah add" and "buildah copy" will attempt to access excluded paths

### ISSUE THREAD

**Issue by eduardosm** [containers/buildah#6166]
### Issue Description

Passing `--exclude` to `buildah add` or `buildah copy` will not keep buildah from trying to accessing the excluded paths, causing it to fail it there are not enough permissions.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Mount an ext4 filesystem in `<mount-path>` (it should contain a `lost+found` directory only readable by root)
2. `buildah from --name test scratch`
3. `buildah add --exclude "**/lost+found" test <mount-path> /` (or `buildah copy`)

### Describe the results you received

```
Error: adding content to container "test": reading "<mount-path>": copier: get: "<mount-path>"("<mount-path>"): opening directory for adding its contents to archive: open <mount-path>/lost+found: permission denied
```

### Describe the results you expected

Since `--exclude "**/lost+found"` should exclude any file or directory named `lost+found`, it should not be attempting to access `<mount-path>/lost+found`.

### buildah version output

```yaml
Version:         1.39.3
Go Version:      go1.24.1
Image Spec:      1.1.0
Runtime Spec:    1.2.0
CNI Spec:        1.1.0
libcni Version:  
image Version:   5.34.2
Git Commit:      
Built:           Wed Mar 19 13:17:19 2025
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

### buildah info output

```yaml
{
    "host": {
        "CgroupVersion": "v2",
        "Distribution": {
            "distribution": "fedora",
            "version": "42"
        },
        "MemFree": 5102845952,
        "MemTotal": 33523478528,
        "OCIRuntime": "crun",
        "SwapFree": 6685831168,
        "SwapTotal": 8589930496,
        "arch": "amd64",
        "cpus": 20,
        "hostname": "eduardosm-pc",
        "kernel": "6.14.5-300.fc42.x86_64",
        "os": "linux",
        "rootless": true,
        "uptime": "24h 40m 49.54s (Approximately 1.00 days)",
        "variant": ""
    },
    "store": {
        "ContainerStore": {
            "number": 1
        },
        "GraphDriverName": "overlay",
        "GraphOptions": null,
        "GraphRoot": "/home/eduardosm/.local/share/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "btrfs",
            "Native Overlay Diff": "true",
            "Supports d_type": "true",
            "Supports shifting": "false",
            "Supports volatile": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 11
        },
        "RunRoot": "/run/user/1000/containers"
    }
}
```

### Provide your storage.conf

```toml
Non-existent
```

### Upstream Latest Release

No
